gdk/commands/component/init.py
**Issue #, if available:** #33
Ensure arguments to `shutil.move` are strings.
Failure on `gdk component init`
Manually
```
gdk component init -t HelloWorld -l python
```
**Checklist:**
=> Fix failure in shutil.move

gdk/commands/component/build.py, tests/gdk/commands/component/test_build.py
Remove dir_exist_ok in shutil copytree as it is already taken care by the cleaning the zip-build folder before copying. 
As zip-build is incompatible with py versions < 3.8, we need to change this. 
**Checklist:**
=> fix(zip-build): remove directory check while copying

.github/workflows/CI.yml, uat/test_uat_CLIParser.py
#33 
Add basic user acceptance tests for CLI list and init commands. 
Helps in testing python builtin functions per versions without mocking them. 
https://github.com/aws-greengrass/aws-greengrass-gdk-cli/actions/runs/1574368234/workflow
This workflow runs added UATs at this state of repo https://github.com/aws-greengrass/aws-greengrass-gdk-cli/commit/615e2aab6a5c3072ea0e89757d2a5c78de85cce6 which results in the issue error - 
- ubuntu https://github.com/aws-greengrass/aws-greengrass-gdk-cli/runs/4510503798?check_suite_focus=true#step:8:356
- windows https://github.com/aws-greengrass/aws-greengrass-gdk-cli/runs/4510504027?check_suite_focus=true#step:6:357
**Any …
=> test(uat): add cli list and init uats

.github/ISSUE_TEMPLATE/config.yml
Use AWS re:post instead of AWS forum. 
**Checklist:**
=> chore(issue): switch from forums to re:Post

gdk/commands/component/publish.py, gdk/static/cli_model.json, gdk/static/cli_model_schema.json, tests/gdk/commands/component/test_publish.py
Publish command now takes in additional argument (optional) for the bucket name. 
Using gdk-config.json file, customers can only provide bucket prefix to which account and region are appended. To provide customers with the ability to use the bucket of their choice, adding this optional argument for passing in exact bucket name.  
Updated unit tests. 
**Checklist:**
=> feat(bucket): pass bucket name in publish command

gdk/commands/component/init.py, gdk/common/exceptions/error_messages.py, gdk/static/cli_model.json, gdk/static/cli_model_schema.json, tests/gdk/commands/component/test_init.py, tests/gdk/commands/component/test_publish.py
Name argument  passed with the init command is used to create a new directory in which the component template/repository are initialized. This argument is optional. 
If customers dont pass this in, the project is initialized in the current directory only if it is empty. 
Currently, initializing a component project with the greengrass-cli tool can be done only in an empty directory. So customer had to create this directory before using the tool.
With this change, customer can provide the name of the directory as an optional argument to the init command, so that the tool can create a new directory and initialize the project there. 
Added new unit tests. 
**Any additional …
=> feat(name): pass project directory in init command

gdk/CLIParser.py, gdk/common/configuration.py, gdk/common/utils.py, integration_tests/gdk/common/test_integ_utils.py, tests/gdk/commands/component/test_publish.py, tests/gdk/common/test_configuration.py, tests/gdk/common/test_utils.py, tests/gdk/static/invalid_gdk_version.json, tests/test_CLIParser.py
GDK CLI releases are maintained on GitHub using tags. This code change assumes that the latest version of the cli tool is maintained at [gdk/_version.py](https://github.com/aws-greengrass/aws-greengrass-gdk-cli/blob/main/gdk/_version.py). This is considered at the latest version of the tool at any given time.
- At the beginning of parsing every cli command, same file but in the locally installed version of the cli tool library is compared with the latest version file on GitHub repo.  If the installed gdk version is smaller than the latest, INFO log is displayed. If for some reason, the tool is not able to fetch the latest version or if the installed gdk version is same as the latest one, we proceed executing the command. Either way, …
=> feat(version-check): check if cli version is up to date

README.md, requirements.txt
- Update readme to download 1.0.0 version of gdk using the tag instead of pulling the version on the main.
- Update requirements file to include packaging library as dependency. 
Without this change, customers cannot download 1.0.0 stable version of GDK-CLI. Even if they want to try the version on main, required dependency is missing. So this change fixes it. 
**Checklist:**
=> chore(version): update gdk version and requirements

.github/workflows/CI.yml
Recently there was breaking change which impacted cli installation. This was not caught in CI step of integration because dependencies in `test-requirement.txt` were different than actual cli dependencies in  `requirement.txt`. One option is to ensure that both list of dependencies are same, but that means we install test dependencies during runtime which is unnecessary. 
This fix is alternative approach to ensure that we install GDK as customer would and verify that its installed correctly.
E.g. workflow failure if GDK is not installed correctly: https://github.com/aws-greengrass/aws-greengrass-gdk-cli/actions/runs/1748076300
E.g workflow successful  if GDK is installed correctly: …
=> chore(workflow): Adding CI step to ensure that gdk is installed successfully

gdk/commands/component/publish.py, gdk/common/parse_args_actions.py, tests/gdk/commands/component/test_init.py, tests/gdk/commands/component/test_publish.py, tests/gdk/common/test_parse_args_actions.py, uat/test_uat_CLIParser.py
- Improve handling of incorrect commands. 
- Create s3 bucket only when there are artifacts to upload. 
Code cleanup
**Checklist:**
=> refactor(cleanup): improve parsing, bucket creation & cleanup

gdk/commands/component/build.py, gdk/commands/component/publish.py, gdk/common/utils.py, tests/gdk/commands/component/test_build.py, tests/gdk/commands/component/test_publish.py
This change allows gdk to create recipes with artifacts that exist in either s3 or local build folders of gdk.
*Current behavior:* 
We parse artifact URIs in the recipe and check for only those artifacts that have s3:// prefix to avoid uris that are docker images. For the ones with s3:// prefix, we check if the files exist in the build folder. If not, the tool exits with an error. 
To support remote s3 uris,
*New behavior:* With this change, we don't exit immediately but check for the artifact in s3 as well. Thus, supporting both local build artifacts and s3 uris in the recipe. 
Currently, we only support local artifacts that are built using gdk build system. There may be cases where some artifacts …
=> feat(s3-uri): support s3 artifacts during build

.github/workflows/CI.yml
- Update commitlint version of the github action and add user friendly name to it. 
- Refactor code to run commit message check before other steps in the workflow to fail fast.
-  Run flake before testing to fail fast. Flake exits with non-zero for any violation. 
- Increase minimum code coverage required to 90%
- Do not run UATs with unittests and integration_tests. Adding it as a separate step as UATs sometimes  need additional dependencies like maven or gradle which are not required for running unit tests and integration tests.
**Checklist:**
By submitting this pull request, I confirm that you …
=> chore(workflow): update commitlint + refactor

gdk/commands/component/build.py, gdk/static/project_build_schema.json, gdk/static/project_build_system.json, tests/gdk/commands/component/test_build.py
`gdk component build `command on windows fails as shown below when run with Java HelloWorld template similar to the [UAT failure](https://github.com/aws-greengrass/aws-greengrass-gdk-cli/runs/5071659549?check_suite_focus=true#step:9:37). 
```
C:\Users\ins\gdk-maven>gdk component build
WARNING:root:This component is identified as using 'maven' build system. If this is incorrect, please exit and specify custom build command in the 'gdk-config.json'.
=============================== ERROR ===============================
Failed to build the component with the given project configuration.
Error building the component with the given build system.
[WinError 2] The system cannot find the file specified
-- 
```
This is because we run …
=> fix(build): fix default build on windows

gdk/commands/component/build.py, tests/gdk/commands/component/test_build.py
- Use `is_file()` to check if the artifact exists instead of `glob` to find the file that match the artifact name. 
- Using `glob` resulted in a bug on windows due to its case insensitive file system. 
In the zip-build system, when `HelloWorld.zip` is looked up in folder `zip-build/` using glob, it resulted in a list with file path - `/abs-path-to-the-file/helloworld.zip` on windows (case insensitive). 
This [file path](https://github.com/aws-greengrass/aws-greengrass-gdk-cli/blob/main/gdk/commands/component/build.py#L351) is used to copy the file from `zip-build/` to `greengrass-build/` resulting in a `helloworld.zip` inside the greengras-build folder instead of `HelloWorld.zip`which conflicts with …
=> fix(build): find artifact with is_file instead of glob

gdk/commands/component/init.py, tests/gdk/commands/component/test_init.py
Checks for conflicting arguments in the `init` command before performing directory operations such as checking if the current directory is empty or creating a new directory based on `name` arg. 
- In the cases where `init` command is run with both `name` and other conflicting arguments, new directory with `name` is created first before the command is exited with conflicting arguments exception.
If the customer corrects the  arguments in the command and runs again, now the command exists with directory exception and it is not customer friendly. 
With this change, the command exists with an exception first even before creating an empty directory. 
**Any additional …
=> refactor(init): check conflicting args before directory

.github/workflows/CI.yml, uat/t_utils.py, uat/test_uat_publish.py
- UATs for publish command with and without building the component.  
- Use https://github.com/aws-actions/configure-aws-credentials to manage credentials for session. ToDo: Update this to use other account. This PR is only for testing. 
**Checklist:**
=> test(publish): uat of publish command using aws-actions 

gdk/commands/component/build.py, gdk/static/project_build_schema.json, gdk/static/project_build_system.json, tests/gdk/commands/component/test_build.py, uat/t_utils.py, uat/test_uat_build.py
- Correctly identifies the build folders for a specific build system. 
- Updated unit tests as needed. 
Instead of recursively finding the intersection of parents directories of build files and build folders in a given project which fails when there are multi-path build folders (a/b/c), we first identify the list of directories with build files in a project. We then iterate through this list and check if build folders also exist within them. 
This change properly identifies the project directories with build file (pom.xml, build.gradle) and build folders (target/, build/libs) recursively. 
- Added UAT for gradle build system with multiple projects. 
- Added UAT for …
=> fix(gradle): identify build folders properly

integration_tests/gdk/components/test_integ_init.py
Add integration tests for init command. 
**Checklist:**
=> test(init): add integration tests for init

gdk/CLIParser.py, gdk/__init__.py, gdk/common/consts.py, gdk/common/utils.py
Set basic config of the root logger in gdk `__init__` to make sure that root logger is configured first with the basic config before using it anywhere. This is because root logger ignores any config set on it after its default values are set unless we use force arg (available onlt in py3.8 or above). 
The basic config set in the current GDK doesn't work on versions < py 3.8 as force=True is not available. So, WARNING is set at as default and the log formatter is also not  applied as expected resulting in logs like  https://github.com/aws-greengrass/aws-greengrass-gdk-cli/runs/5150912788?check_suite_focus=true#step:11:23 instead of https://github.com/aws-greengrass/aws-greengrass-gdk-cli/runs/5225356195 …
=> fix(logging): set logging basic config in gdk module __init__

integration_tests/gdk/components/test_integ_BuildCommand.py, integration_tests/gdk/components/test_integ_PublishCommand.py, tests/gdk/commands/component/test_BuildCommand.py
Adding integration tests for build and publish commands with 90% coverage. 
**Checklist:**
=> test(integ): add integ tests for build & publish

gdk/commands/component/BuildCommand.py, gdk/commands/component/component.py, gdk/common/exceptions/BuildError.py, gdk/common/exceptions/error_messages.py, integration_tests/gdk/components/test_integ_BuildCommand.py, tests/gdk/commands/component/test_BuildCommand.py, uat/test_uat_build.py
Add custom build exceptions to catch different kinds of errors with the build command. 
All exceptions are raised the same way with a reason and a solution. These are all caught at the top level keeping the exception message less redundant. 
**Checklist:**
=> refactor(build): use custom exceptions in build

.github/workflows/CI.yml, README.md, uat/conftest.py, uat/t_setup.py, uat/test_uat_build.py, uat/test_uat_init.py, uat/test_uat_list.py, uat/test_uat_publish.py
Refactor UATs to emit code coverage metrics if executed in that mode.
To identify metric driven coverage from UAT tests.
Run the test locally in:
1. with installed gdk cli mode
* `coverage run --source=gdk -m pytest -v -s uat`
1. with code coverage mode
* `coverage run --source=gdk -m pytest -v -s uat --instrumented`
With existing UATs the code coverage shown is 77%.
**Checklist:**
=> test(uat): migrate tests to use gdk_cli abstraction

.github/workflows/CI.yml, uat/README.md, uat/conftest.py, uat/pytest.ini, uat/t_utils.py, uat/test_uat_build.py, uat/test_uat_init.py, uat/test_uat_publish.py
Add multiple gdk versions to verify regression between latest and old gdk versions.
1. Add new option --target-version to pass the expected the gdk-cli versions to UATs.
* Example:
*  `pytest -v -s uat --target-version 1.0.0`
*  `pytest -v -s uat --target-version 1.1.0`
*  `pytest -v -s uat --target-version HEAD`
* If not provided then target version defaults to `HEAD`, which translates to the code at the most recent commit against which the regression workflow is running.
2. Add `@pytest.mark.version(...)` test marker to provide version constraints for any UAT test.
* The marker takes `kwargs` (key & values) to define constraints. These can be combined to create upper and lower bounds. Available key args are:
* `eq`: equal to gdk cli …
=> chore(regression): regression test old gdk version

.flake8, .github/workflows/CI.yml, .pre-commit-config.yaml, CONTRIBUTING.md, README.md, requirements.txt, test-requirements.txt, uat/README.md
Added pre-commit hooks to run flake8 automatically before commits.
Also updated `CONTRIBUTING.md` as the developers would need to run one time command to make `pre-commit` work.
Run flake8 automatically saves developers time, as our CI workflow enforces the same rules.
By running git commit locally.
**Checklist:**
=> chore: add pre-commit hooks with flake8

.github/workflows/auto-approve.yml
Make auto-merge more stricter and only limited to dependabot PRs.
Without strict PR creator check, any other actor can create a PR and put an auto-approve label on it and try to spoof a dependency update PR. This could lead to automatically merging code from unknown actors.
**Checklist:**
=> chore: add stricter constraints on auto-approve flow

README.md
https://github.com/aws-greengrass/aws-greengrass-gdk-cli/issues/93
Update README to add steps on how to configure `gdk-config.json`.
Without this change a user might skip `gdk-config.json` and end-up with broken *getting started* experience.
**Checklist:**
=> docs: update readme with gdk-config.json config step

.github/workflows/auto-approve.yml
Change auto-approve workflow to only run after CI workflow has finished successfully.
As of now, auto-approve workflow executes in parallel to CI workflow. For dependabot pull requests, there is a risk that auto-approve workflow might merge prematurely before CI workflow completes. Making these workflows sequential mitigates that risk.
**Checklist:**
=> feat: run auto-approve after CI workflow

.github/workflows/CI.yml, .github/workflows/Regression.yaml
This PR updates the GitHub workflow actions to 
- Run regression tests only when the code changes are pushed on to main or development branches. Running them for every PR commit/change is not needed.
- Do not run workflow steps such as configuring aws credentials and UATs  when the PR comes from external contributors due to security reasons. 
**Checklist:**
=> chore: update github workflows

gdk/commands/component/BuildCommand.py, tests/gdk/commands/component/test_BuildCommand.py, uat/component_build.feature
Add support for Gradle's Kotlin DSL by adding "build.gradle.kts" to the list of build files GDK searches for when the build system is set to "gradle"
Without this change anyone using Gradle's Kotlin DSL would receive an error message like the one below when attempting to run `gdk component build`:
```
[2022-03-17 22:00:20] WARNING - Could not find the artifact file 'HelloWorld-1.0.0.jar' in the build folder 'set()'.
```
I built a Greengrass component that uses Gradle's Kotlin DSL and published it successfully
=> Added support for Gradle’s Kotlin DSL

gdk/commands/component/BuildCommand.py, gdk/static/config_schema.json, gdk/static/project_build_schema.json, gdk/static/project_build_system.json, integration_tests/gdk/components/test_integ_BuildCommand.py, tests/gdk/commands/component/test_BuildCommand.py, uat/component_build.feature, uat/steps/component.py, uat/t_utils.py
**Issue:**
https://github.com/aws-greengrass/aws-greengrass-gdk-cli/issues/84
Added support for using Gradle wrapper scripts AKA "./gradlew"
Gradle wrappers enforce that a build uses the proper version of Gradle. Without this change components will be built with the system's Gradle command which may be the wrong version.
I built a component locally with it
=> feat: add support for using Gradle wrapper scripts

gdk/commands/component/BuildCommand.py, integration_tests/gdk/components/test_integ_BuildCommand.py
A part of #97 to exit when the build fails is covered here. 
Exit build when the build command files. This is a bug if a component is published without build. i.e if `gdk component publish` is run `gdk component build` is also run if the component is not built. In this case, if build fails, we publish command should exit as well. Without this change, even if the build fails, component is published.
We can check for the sub-process return code to see if the build succeeded. we're check=True also does the same thing  along with printing the output of the command. 
**Checklist:**
By submitting this …
=> fix: exit build when the command fails

gdk/build_system/BuildSystem.py, gdk/build_system/Zip.py, gdk/commands/component/BuildCommand.py, tests/gdk/build_system/test_BuildSystem.py, tests/gdk/build_system/test_Zip.py, tests/gdk/commands/component/test_BuildCommand.py, tests/helpers/project_config.py
Solves https://github.com/aws-greengrass/aws-greengrass-gdk-cli/issues/109 as well.
Reads the `exclude` configuration from the zip build options and if present it will exclude the files defined + the gdk exclusive files and build folders.
Allow users to have more control over the files they would like to get zipped.
unit test  + uats
=> feat: exclude files specified by user

gdk/commands/component/PublishCommand.py, gdk/commands/component/project_utils.py, gdk/static/config_schema.json, integration_tests/gdk/components/test_integ_PublishCommand.py, tests/gdk/commands/component/test_PublishCommand.py
This enhancement will allow users to choose an encryption type while uploading the GDK artifact(s) to s3 or if chosen the  code will lookup the default bucket encryption type and use that.  This enhancement also will allow users to add metadata to the artifact(s) that are being uploaded. 
**Supported Encryption Values:** 
_alias_ : Which would use a kms key alias for encrypting the gdk artifact
example 
```
"publish": {
"bucket": "this-is-a-test",
"region": "us-east-1",
"encrypt": {
"server_side_encryption": "aws:kms",
"kms_key_id": "alias/gdk-test"
}
}
```
_kms key arn_ : This option would use a kms key arn for encrypting the gdk artifact
example : 
```
"publish": {
"bucket": "this-is-a-test",
"region": "us-east-1",
"encrypt": { …
```
=> added encryption and metadata to artifact upload

gdk/commands/component/PublishCommand.py, gdk/common/exceptions/CommandError.py, gdk/static/cli_model.json, integration_tests/gdk/components/test_integ_PublishCommand.py, tests/gdk/commands/component/test_PublishCommand.py
gdk configuration supports bucket, region and options parameters under publish key. These configuration values as used with `gdk component publish` command. The cli publish command takes in `bucket` name as argument. 
With this change, region and options configuration values can also be provided as arguments to the publish command. 
`gdk component publish -r <region-name> -o <options-json-string>`. If these values are provided in both the gdk config file and as arguments in the publish command, the cli arguments override the gdk config values.   
**Checklist:**
By submitting this pull request, I …
=> feat: add region and options args in publish command

gdk/commands/component/PublishCommand.py, tests/gdk/commands/component/test_PublishCommand.py
Fixes bug where boto client creation is not using the right region
The `--region` arg won't work as expected.
Unit and manual testing
=> fix: fix boto3 client regions

gdk/aws_clients/Greengrassv2Client.py, gdk/commands/component/PublishCommand.py, gdk/common/utils.py, integration_tests/gdk/components/test_integ_PublishCommand.py, tests/gdk/aws_clients/test_Greengrassv2Client.py, tests/gdk/commands/component/test_PublishCommand.py, tests/gdk/common/test_utils.py
These changes create a new adapter class for performing Greengrassv2 client operations based on the project config.
**Checklist:**
=> refactor: move GGv2 client out from the publish command class

gdk/aws_clients/S3Client.py, gdk/commands/component/PublishCommand.py, integration_tests/gdk/components/test_integ_PublishCommand.py, tests/gdk/aws_clients/test_S3Client.py
#138 
Base commit https://github.com/aws-greengrass/aws-greengrass-gdk-cli/commit/0d28f97566d648f0dede47903e61b9cef919b7f9 from PR https://github.com/aws-greengrass/aws-greengrass-gdk-cli/pull/124
Since Greengrass supports only artifacts from the same account and region as of the components', before creating the bucket, GDK now checks for the bucket location using `get_bucket_location` API. This API works only when it is called by the bucket owner. The output of this API contains location (region) of the bucket. 
- If the user of the command is not the owner of the bucket, `get_bucket_location` throws an exception
- `404 - Not found` Bucket does not exist, GDK can create a new bucket.
- `403 - Forbidden` Bucket already exists but is …
=> fix: check for bucket's existence

gdk/static/config_schema.json, tests/gdk/build_system/test_zip_build_configuration.py, uat/component_build.feature, uat/steps/component.py, uat/t_utils.py
#143 
Fixes typo in `excludes` option of GDK config schema. 
- This change is needed to correctly exclude the files during zip and also match the documentation. 
- Added a new UAT that verifies the option and also the files in the final zip artifact. 
- Failed UAT run: https://github.com/aws-greengrass/aws-greengrass-gdk-cli/actions/runs/4558031750/jobs/8040432001?pr=149#step:15:7903
- Passing UAT run after updating schema: https://github.com/aws-greengrass/aws-greengrass-gdk-cli/actions/runs/4558111632/jobs/8040600772?pr=149
TODO: The minimum version of this UAT must be bumped to 1.2.2 - Will do that in the follow up PR. 
**Any additional information or context …
=> fix: fix excludes typo in config schema & add a UAT to verify

gdk/commands/component/project_utils.py, integration_tests/gdk/components/test_integ_project_utils.py, tests/gdk/commands/component/test_project_utils.py
This is covered in the `CaseInsensitiveRecipeFile` class as `read()` method. PR: https://github.com/aws-greengrass/aws-greengrass-gdk-cli/pull/141
**Checklist:**
=> chore: remove parse recipe from project utils

uat/steps/gdk_cli.py
AWS resources are cleaned up after each scenario if the last command used is of type `gdk component publish`. 
The last command type used is not set properly all this time (set as `c o`  for any command type) and so the resources created were cleaned up resulting in exceeding the limit for number of components (5000). 
**Checklist:**
=> test: fix last command type to cleanup aws resources properly

gdk/CLIParser.py, gdk/aws_clients/Greengrassv2Client.py, gdk/aws_clients/S3Client.py, gdk/build_system/Zip.py, gdk/commands/component/BuildCommand.py, gdk/commands/component/InitCommand.py, gdk/commands/component/ListCommand.py, gdk/commands/component/PublishCommand.py, gdk/commands/component/component.py, gdk/commands/component/transformer/BuildRecipeTransformer.py, gdk/commands/component/transformer/PublishRecipeTransformer.py, integration_tests/gdk/components/test_integ_BuildCommand.py, integration_tests/gdk/components/test_integ_InitCommand.py, integration_tests/gdk/components/test_integ_ListCommand.py, integration_tests/gdk/components/test_integ_PublishCommand.py, tests/gdk/aws_clients/test_Greengrassv2Client.py, tests/gdk/aws_clients/test_S3Client.py, tests/gdk/commands/component/test_BuildCommand.py, tests/gdk/commands/component/test_InitCommand.py, tests/gdk/commands/component/test_ListCommand.py, tests/gdk/commands/component/test_PublishCommand.py, tests/gdk/commands/component/test_component.py, uat/component_build.feature, uat/t_setup.py
Print full exception trace when the command fails. 
- Log messages as errors and propagate the exception all the way up. 
- Update tests to reflect the same. 
- Add debug level logs wherever applicable. 
**Checklist:**
=> refactor: exit commands with full exception message + add debug logs

README.md, gdk/aws_clients/S3Client.py, gdk/common/CaseInsensitive.py, tests/gdk/aws_clients/test_S3Client.py, tests/gdk/common/test_CaseInsensitive.py, tests/gdk/static/project_utils/valid_component_recipe.json, tests/gdk/static/project_utils/valid_component_recipe.yaml
**Issue #, if available:** None
**Description of changes:** Fix doc and implementation for non-existing buckets. Fix list expansion.
**Why is this change necessary:** New projects without bucket don't work
**How was this change tested:** Manual test with non-existing and non-accessible bucket, unit tests changed
Issue 1 reproduction:
- Run `component build` and `component publish` on a new project without an existing bucket
Issue 2 reproduction:
- Create a component recipe like this: https://github.com/awslabs/aws-greengrass-labs-bluetooth-gateway/blob/main/src/recipe.json
- Run `component build`
- Check `greengrass-build/recipe.json` and see that `operations` and `resources` are now empty lists
--> this will cause …
=> fix: bucket creation and parsing lists in recipe

Makefile, README.md, integration_tests/gdk/telemetry/integration_base.py, integration_tests/gdk/telemetry/test_server_setup.py, test-requirements.txt
As part of collecting telemetry data we want to ensure the correct data and payloads are submitted to the service. 
* Create test telemetry server to ensure data is sent upon running a gdk command.
Ensure we test telemetry from the user's standpoint
Run integration tests `make tests_integration`
=> feat: setup fake server to test telemetry requests are sent upon running commands

gdk/CLIParser.py, gdk/commands/Command.py, gdk/common/model_actions.py, gdk/static/cli_model.json, gdk/static/cli_model_schema.json, integration_tests/gdk/common/test_integ_model_actions.py, tests/gdk/common/test_model_actions.py, tests/test_CLIParser.py
CLI tool is built from a JSON model file which provides commands, sub-commands, arguments and everything else that is needed to build CLI using arg parse. Existing JSON structure is not extendable as it does not allow `init` as a subcommand for any commands other than "component". 
```
{
"gdk": {
"sub-commands": [
"component"
],
"help": "Greengrass development kit - CLI for developing AWS IoT GreengrassV2 components."
},
"component": {
"sub-commands": [
"init"
],
"help": "Initialize, build and publish GreengrassV2 components using this command."
},
"init": {
....
}
}
```
This PR changes the structure to as shown below so each command can have their own sub-commands. 
```
{
"gdk": {
"sub-commands": [
"component": {
"sub-commands": [ …
```
=> refactor: update cli model by grouping the sub-commands by command

gdk/CLIParser.py, gdk/telemetry/emit.py, gdk/telemetry/metric.py, gdk/telemetry/telemetry.py, integration_tests/gdk/telemetry/telemetry_base.py, integration_tests/gdk/telemetry/test_emit_telemetry.py, tests/gdk/telemetry/test_emit.py, tests/gdk/telemetry/test_metric.py, tests/helpers/telemetry_fake.py
Emits install metric by default telemetry is disabled. There will be follow up requests  to ensure we don't emit metric on the same thread and that if emitting fails it doesn't stop the command from running.
unit + integ tests
=> feat: emit basic install metric

gdk/runtime_config.py, gdk/telemetry/emit.py, gdk/telemetry/telemetry.py, integration_tests/gdk/telemetry/telemetry_base.py, integration_tests/gdk/telemetry/test_emit_telemetry.py, integration_tests/gdk/telemetry/test_telemetry_setup.py, tests/test_runtime_config.py
This PR adds Runtime Config which is basically a singleton we can use to store information we need to store for subsequent runs. Currently the object is not thread safe but we could implement locking later.  It is used so we record if we have already emitted the installed metrics and will be used to record if we have shown the user the install prompt.
The runtime config is just meant to hold key value pairs. If we ever decided to change keys in the config in a future version we would have to nix it and recreate it or use a different name and ignore the old one. The only harm tampering with the file is that the user MAY cause it to trigger other an install metric one more time. When we load it we only take in the keys that we define on the app, the rest are …
=> Emit install metric only once.

gdk/commands/methods.py, gdk/commands/test/test.py, gdk/static/cli_model.json, gdk/static/cli_model_schema.json, integration_tests/gdk/telemetry/telemetry_base.py, integration_tests/gdk/test_integ_CLIParser.py
Add `test` sub-command to gdk cli. 
With this change, gdk can now support 
- `gdk test init `
- `gdk test run`
**Checklist:**
=> feat: add test subcommand

gdk/commands/test/InitCommand.py, gdk/commands/test/test.py, gdk/common/utils.py, integration_tests/gdk/test/test_integ_uat_InitCommand.py
When `gdk test init`command is run, `TestTemplateForCLI` from component templates [repo](https://github.com/aws-greengrass/aws-greengrass-component-templates) is downloaded into a new directory called `uat-features` at the current path. 
If `uat-features` directory already exists at the current path, then the commands exits with a WARNING message. Existing folder is not overridden or replaced. 
**Checklist:**
=> feat: implement test init command

gdk/build_system/GDKBuildSystem.py, gdk/build_system/Gradle.py, gdk/build_system/GradleWrapper.py, gdk/build_system/Maven.py, gdk/build_system/UATBuildSystem.py, integration_tests/gdk/build_system/test_GDKBuildSystem.py, integration_tests/test_data/maven/pom.xml, tests/gdk/build_system/test_UATBuildSystem.py
Adding classes for build system supported by GDK for UATs. Supported build system were initially provided as a static JSON file. Component build system will be refactored to use these build system classes in future. 
Needed by `gdk test build` command
Added unit tests. These will be covered in integration tests when the command is added. 
**Checklist:**
=> feat: add supported build systems for UATs

gdk/commands/methods.py, gdk/commands/test/test.py, gdk/static/cli_model.json, integration_tests/gdk/test_integ_CLIParser.py
Adds build command to the cli model.  With this change, customers can run `gdk test build` command using the CLI. 
**Checklist:**
=> feat: add test build command to the cli model

gdk/commands/test/BuildCommand.py, gdk/commands/test/test.py, integration_tests/gdk/test/test_integ_uat_BuildCommand.py, integration_tests/test_data/recipes/build_recipe.yaml, tests/gdk/commands/test/test_uat_BuildCommand.py
Implement `gdk test build` command which is responsible for building the UAT module set up by the customer using OTF testing standalone jar as a dependency. Before building the module, the following steps are performed in order:
1. Remove the `uat-features` folder from `greengrass-build` directory. 
2. Copy the `uat-features` folder from gdk project to the `greengrass-build` directory. This is to avoid updating the original feature files. 
3. Update the feature files that contain the strings `GDK_COMPONENT_NAME` and `GDK_COMPONENT_RECIPE_FILE` with component name and uat_recipe path. 
4. Create uat_recipe file only when there's at least one feature file with `GDK_COMPONENT_RECIPE_FILE` variable. This UAT recipe file is created from …
=> feat: implement gdk build command

gdk/commands/test/RunCommand.py, gdk/commands/test/test.py, tests/gdk/commands/test/test_uat_RunCommand.py
Initial implementation of test run command.  
This method is called when `gdk test run` is executed. Before running the UAT jar, run command verifies if the testing module is already built by checking the build folder. If it not built, then an exception is thrown. 
**Checklist:**
=> feat: initial implementation of test run command

gdk/commands/test/config/RunConfiguration.py, tests/gdk/commands/test/config/test_RunConfiguration.py
This helper class is added to read and validate configuration provided in both `gdk-config.json` and  as `run` command arguments.
The `RunConfiguration` class validates `tags` and `ggc-archive`  provided in the `otf_options` configuration. If these options are not provided, then default values are used as these are required to the run the testing jar. 
**Checklist:**
=> feat: add helper class to read config of run command

gdk/commands/test/RunCommand.py, gdk/commands/test/config/RunConfiguration.py, tests/gdk/commands/test/test_uat_RunCommand.py
if `ggc-archive` is not configured in the `gdk-config.json` file, then the default value is set to path `greengrass-build/greengrass-nucleus-latest.zip`. 
If nucleus archive does not exist at that location, then the latest version of nucleus is downloaded from URL. 
**Checklist:**
=> feat: download nucleus archive to default path

gdk/commands/test/RunCommand.py, tests/gdk/commands/test/test_uat_RunCommand.py
Runs the testing jar with configured options as arguments. 
Sample command
```
java -jar <path-to-testing-jar> --tags=<tags> --ggc-archive=<path-to-greengrass-nucleus-zip>
```
**Checklist:**
=> feat: run testing jar with configured options

gdk/commands/test/InitCommand.py, gdk/common/config/TestConfiguration.py, integration_tests/gdk/common/config/test_GDKProject.py
Remove redundant test configuration and fix `init` command. 
**Checklist:**
=> fix: init command + do not read tags and archive path in TestConfig

gdk/commands/component/InitCommand.py, integration_tests/gdk/components/test_integ_InitCommand.py, tests/gdk/commands/component/test_InitCommand.py
#100
This change creates a new directory only after the component is successfully downloaded and extracted. 
If the component download fails or if the component does not exist, new project directory is not created. 
Also, gdk will not throw an exception now if the directory already exists as long as it is empty. 
**Checklist:**
=> fix: create a new dir only if the component download succeeds

gdk/commands/component/InitCommand.py, gdk/commands/test/InitCommand.py, gdk/common/URLDownloader.py, integration_tests/gdk/components/test_integ_InitCommand.py, tests/gdk/commands/component/test_InitCommand.py, tests/gdk/common/test_URLDownloader.py
Add a utility method `download_and_extract` in the `URLDownloader` class and refactor `component init` and `test init` code to use the same.  Updated tests. 
**Checklist:**
=> refactor: add utility method to download and extract and refactor init methods

gdk/commands/component/project_utils.py, gdk/commands/test/RunCommand.py, integration_tests/gdk/test/test_integ_uat_RunCommand.py, integration_tests/test_data/config/config.json, tests/gdk/commands/test/test_uat_RunCommand.py
Add integration tests for the `gdk test run` command.
**Checklist:**
=> test: add integration tests for run command

gdk/build_system/E2ETestBuildSystem.py, gdk/commands/methods.py, gdk/commands/test/BuildCommand.py, gdk/commands/test/InitCommand.py, gdk/commands/test/RunCommand.py, gdk/common/consts.py, gdk/common/parse_args_actions.py, gdk/static/cli_model.json, gdk/static/cli_model_schema.json, integration_tests/gdk/build_system/test_GDKBuildSystem.py, integration_tests/gdk/test/test_integ_uat_BuildCommand.py, integration_tests/gdk/test/test_integ_uat_InitCommand.py, integration_tests/gdk/test/test_integ_uat_RunCommand.py, integration_tests/gdk/test_integ_CLIParser.py, tests/gdk/build_system/test_UATBuildSystem.py, tests/gdk/commands/test/test_uat_BuildCommand.py, tests/gdk/commands/test/test_uat_RunCommand.py, uat/steps/constants.py, uat/test_init.feature
Rename the UAT occurrences to E2E testing in gdk cli commands, class and variables names and tests. 
**Checklist:**
=> refactor: rename uat to e2e test

gdk/commands/test/InitCommand.py, gdk/commands/test/config/InitConfiguration.py, gdk/static/cli_model.json, gdk/static/cli_model_schema.json, integration_tests/gdk/test/test_integ_uat_InitCommand.py
- Add a new arg `otf_version` that can be passed with `gdk test-e2e init` command. This command overrides the OTF version provided in the config. 
**Checklist:**
=> feat: add otf_version arg to the test-e2e init command

gdk/build_system/Zip.py, gdk/static/config_schema.json, tests/gdk/commands/component/test_BuildCommand.py, uat/component_build.feature, uat/component_publish.feature, uat/steps/component.py
Add `zip_name` option to the zip build system. Setting zip_name to `""` will have it automatically use the component name (ideally this would become the default over time). If zip_name isn't specified, the current behavior of using the current directory name will be used.
**Checklist:**
=> fix(zip): use the component name as the archive name

gdk/build_system/Zip.py, gdk/commands/component/BuildCommand.py, gdk/commands/component/project_utils.py, integration_tests/gdk/components/test_integ_BuildCommand.py, integration_tests/gdk/components/test_integ_PublishCommand.py, integration_tests/test_data/recipes/hello_world_recipe.yaml
- Use `get_current_directory` wherever applicable. 
- Rewrite build and publish command integ tests by using botocore Stubber and removing all mocks with implementation details. 
**Checklist:**
=> test: Refactor integration tests of build and publish command

gdk/build_system/Zip.py, gdk/commands/component/BuildCommand.py, gdk/commands/component/config/ComponentBuildConfiguration.py, gdk/commands/component/transformer/BuildRecipeTransformer.py, integration_tests/gdk/components/transformer/test_integ_BuildRecipeTransformer.py, tests/gdk/build_system/test_Zip.py, tests/gdk/commands/component/test_BuildCommand.py, tests/gdk/commands/component/transformer/test_BuildRecipeTransformer.py
- Create new `ComponentBuildConfiguration` class that reads build command config. 
- Remove using project configuration as dictionary object. 
- Update tests. 
**Checklist:**
=> refactor: use ComponentBuildConfiguration instead of dictionary

gdk/commands/component/PublishCommand.py, gdk/commands/component/config/ComponentBuildConfiguration.py, gdk/commands/component/config/ComponentPublishConfiguration.py, gdk/commands/component/transformer/PublishRecipeTransformer.py, integration_tests/gdk/components/test_integ_PublishCommand.py, integration_tests/gdk/components/transformer/test_integ_PublishRecipeTransformer.py, tests/gdk/commands/component/config/test_ComponentPublishConfiguration.py, tests/gdk/commands/component/test_PublishCommand.py, tests/gdk/commands/component/transformer/test_PublishRecipeTransformer.py
- Create a new class object `ComponentPublishConfiguration` to hold project configuration in the publish command instead of project config dictionary object.
- Update tests. 
**Checklist:**
=> refactor: use ComponentPublishConfiguration instead of dictionary

uat/steps/test_e2e.py, uat/t_setup.py, uat/test_build.feature
Add 2 new UAT scenarios for testing `gdk test-e2e build` command. 
- As a component builder, when I run the test-e2e build command, test feature files are updated and then the module is built. 
- As a component builder, when I run the test-e2e build command without building the component, the command exits with an error. 
**Checklist:**
=> test: add 2 scenarios for test-e2e build cmd

gdk/commands/test/BuildCommand.py
If a component builder using GDK runs `gdk test-e2e build `command before the project is initialized, an exception is raised with a proper message. 
**Checklist:**
=> fix: raise exc if the test module is missing before build

gdk/common/config/GDKProject.py, gdk/static/cli_model.json, integration_tests/gdk/test/test_integ_uat_RunCommand.py, integration_tests/test_data/config/config.json, tests/gdk/commands/test/config/test_RunConfiguration.py
Replace occurrences of `test` with `test-e2e` in the implementation and as well as tests. 
**Checklist:**
=> fix: use test-e2e instead of test in config

gdk/commands/test/InitCommand.py, integration_tests/gdk/test/test_integ_uat_InitCommand.py
- GDK exits without downloading the test template during test-e2e init if the directory already contains gg-e2e-tests folder. This change checks not only for the folder existence but also if it is empty.
- Updated integration tests accordingly. 
**Checklist:**
=> fix: verify if test dir exists and is not empty before exiting

THIRD-PARTY-LICENSES, gdk/commands/test/InitCommand.py, gdk/commands/test/config/InitConfiguration.py, gdk/common/config/TestConfiguration.py, integration_tests/gdk/common/config/test_GDKProject.py, integration_tests/gdk/test/test_integ_uat_InitCommand.py, requirements.txt, test-requirements.txt, tests/gdk/commands/test/config/test_InitConfiguration.py, uat/steps/test_e2e.py, uat/test_init.feature
- Validate the OTF version provided in the config and the command arguments using `semver` library before downloading the template from GitHub. 
- Update third party licenses.
- Add unit tests for the same. 
**Checklist:**
=> fix: validate OTF version before downloading the template

gdk/commands/test/config/InitConfiguration.py, gdk/commands/test/config/RunConfiguration.py, gdk/common/config/GDKProject.py, uat/component_build.feature
- Update minimum version of GDK for the UAT with zip name feature. 
- Update logging. Raise `ValueError` instead of generic `Exception` and change log levels. 
**Checklist:**
=> fix: min version in uat and logging

gdk/common/configuration.py, gdk/static/config_schema.json, integration_tests/gdk/common/test_integ_configuration.py, tests/gdk/build_system/test_zip_build_configuration.py, tests/gdk/common/test_configuration.py
- validate `gdk_version` in the `gdk-config.json` file with the installed gdk version before validating other config. If gdk_version is not present in the config file, do nothing. 
**Checklist:**
=> fix: validate version before validating config

gdk/static/user_input_recipe_schema.json, tests/gdk/common/test_RecipeValidator.py, tests/gdk/static/sample_recipes/invalid_recipe_extra_property.json, tests/gdk/static/sample_recipes/invalid_recipe_incorrect_value.json, tests/gdk/static/sample_recipes/invalid_recipe_mismatched_type.json, tests/gdk/static/sample_recipes/invalid_recipe_missing_required_property.json, tests/gdk/static/sample_recipes/invalid_recipe_misspelling_property.json, tests/gdk/static/sample_recipes/recipe_case_insensitive.json, tests/gdk/static/sample_recipes/recipe_case_insensitive.yaml, tests/gdk/static/sample_recipes/recipe_gg_client_device_auth.json, tests/gdk/static/sample_recipes/recipe_gg_disk_spooler.json, tests/gdk/static/sample_recipes/recipe_gg_nucleus.yaml, tests/gdk/static/sample_recipes/recipe_gg_secret_manager.yaml
I have added a JSON schema file that defines the user-input recipe format and structure. The schema is based on the existing recipe definition in its Java package and its documentation, which allows for further semantic validation. 
The JSON schema is essential for validating user-input recipes and ensuring they conform to the expected format. By using the schema, we can enforce constraints on the recipe properties and catch any potential errors or invalid input early in the process.
I have tested the JSON schema by validating it against various recipes manually. And all unit tests (including newly added tests) and integration tests passed successfully.
**Any additional …
=> feat: create json schema for user-input recipe

gdk/wizard/ConfigEnum.py, gdk/wizard/WizardConfigUtils.py, requirements.txt
Addition of Config file enum class and utils class used by the wizard 
ENUM class doesn't require testing and Utils class contains glue code only and doesn't need to be tested 
**Checklist:**
=> feat: wizard enums and utils

gdk/wizard/ConfigEnum.py, gdk/wizard/WizardChecker.py, gdk/wizard/WizardData.py, tests/gdk/wizard/test_WizardData.py
Fixed a bug in the wizard
Two main issues: 
- checker and setter for publish and build options:
- ----- was setting strings to be the value for the build and publish options, essentially setting the value to be "{}" instead of {}, etc. 
------- JSON.load doesn't work for string dictionary objects that use single quotes for keys and values, so needed to convert each single quotation with double quotes for both the checkers and the setters 
- Custom Build Command setter:
- ------- automatically sets the input to be a string instead of trying to convert it to a list first
**Checklist:**
By submitting …
=> fix: wizard bug fix

gdk/commands/component/transformer/BuildRecipeTransformer.py, gdk/common/RecipeValidator.py, gdk/static/user_input_recipe_schema.json, tests/gdk/commands/component/transformer/test_BuildRecipeTransformer.py, tests/gdk/common/test_RecipeValidator.py
Added recipe input validation to check specific recipe properties and log a warning if any violations are detected.
This change is necessary to proactively identify and address potential issues during the build stage.
New unit tests have been added and all tests passed successfully.
The decision to display warnings instead of raising errors is based on the understanding that these issues may not be critical enough to block component deployment or runtime. The warnings are intended to alert customers early in the process, allowing them to be aware of and mitigate potential issues.
An example output …
=> feat: add recipe input validation

gdk/commands/component/transformer/BuildRecipeTransformer.py, gdk/common/RecipeValidator.py, gdk/common/consts.py, gdk/common/exceptions/error_messages.py, gdk/common/utils.py, tests/gdk/commands/component/transformer/test_BuildRecipeTransformer.py, tests/gdk/common/test_RecipeValidator.py, tests/gdk/common/test_utils.py
Incorporated a recipe file size validation to ensure the file size remains within the permissible limit of 16KB. Added a verification process for the validity and compatibility of the RecipeFormatVersion, with enhanced error messages for better customer guidance.
This change is crucial to establish a comprehensive recipe validation mechanism, encompassing both size and content checks. By doing so, we enhance the reliability of recipes for downstream processes.
Introduced new unit tests that successfully passed, affirming the functionality. Thoroughly validated the implementation locally to ensure it behaves as intended.
**Any additional information or context required …
=> feat: add recipe file size validation

gdk/common/config/TestConfiguration.py, integration_tests/gdk/common/config/test_GDKProject.py, integration_tests/test_data/config/config_gtf.json, integration_tests/test_data/config/config_gtf_and_otf.json, tests/gdk/commands/test/config/test_InitConfiguration.py, tests/gdk/commands/test/config/test_RunConfiguration.py
Currently, the gdk-config.json file can have "otf_version" and "otf_options" keys under test-e2e. This change updates them to "gtf_version" and "gtf_options", but will still support the use of the older keys. If both are present, it will use the gtf named keys.
OTF ("Open Test Framework") is being renamed to GTF ("Greengrass Test Framework") so this change reflects that in the config file.
Added unit and integ tests to confirm that when both keys are present, we are using the gtf named keys.
This doesn't include changes to revise or add the renaming to command line tags. Will be done in a later PR. …
=> feat: support for both gtf and otf keys in gdk config

gdk/common/CaseInsensitive.py, gdk/common/consts.py, tests/gdk/common/test_CaseInsensitive.py, tests/gdk/static/project_utils/recipe_missing_comma.json
Add better logging during build stage for recipe syntax validation. Before, when a build fails due to a recipe syntax issue it just prints the error that there was some problem during the build. Now, it will notify the user that there was an issue with the recipe syntax and link to the component recipe docs for reference.
Provides more clarity for what is going wrong.
Added unit tests for recipes with a common syntax error.
**Checklist:**
=> feat: better logging for recipe syntax failures during build

gdk/wizard/Prompter.py, requirements.txt, test-requirements.txt, tests/gdk/wizard/test_Prompter.py
Use python built-in input function to prompt for inputs instead of PyInquirer. To use the existing default value users should leave the input field blank. 
PyInquirer does not have a maintainer anymore (https://github.com/CITGuru/PyInquirer/issues/159) and does not work on python versions past 3.10 due to a deprecated import statement in one of PyInquirer's dependent packages. Since we cannot expect this project to be updated and we want to ensure that we support later and current releases of python we cannot use PyInquirer.
Manually tested the changes.
Unit tests don't exist (yet). They will be in …
=> fix: remove pyinquirer dependency to work with python 3.10+

gdk/wizard/Prompter.py, gdk/wizard/WizardChecker.py, gdk/wizard/WizardData.py, tests/gdk/wizard/test_WizardChecker.py, tests/gdk/wizard/test_WizardData.py
Add functionality to prompt for component name in the gdk-config.json file. This will be the first prompt when running `gdk config update -c`. If a name is given, it will change the component name in the gdk-config.json file to the given name, otherwise keep the existing one.
When users are using our provided templates, they are likely going to want to change the component name. Prompting for it will allow users to change it without opening the gdk-config.json file, which is the goal of the gdk config update command.
Manually tested. Also added some unit tests.
I know the two lines in the prompting …
=> feat: prompt for component name during gdk config update

gdk/commands/config/update/ConfigData.py, gdk/commands/config/update/Prompter.py, tests/gdk/commands/config/update/test_ConfigData.py
There were two bugs having to do with publish command prompting.
- When default value is used, a dict is passed which errors due to a string method. Now, we always take a string as the input for default value (as it should be)
- When improper input is passed 3 times, it uses the original value which is a dict. This also errors because of a string method.
Both bugs are fixed and the corresponding string manipulation methods are only used on strings.
Bugfix
Added a new unit test for set_publish_options to cover the case where a dict is passed. This should verify this bug is fixed in future updates. …
=> fix: publish options update does not error when dict

.github/workflows/Regression.yaml
Updating regression workflow versions to test against to 1.3.0 and 1.4.0 so we are accounting for latest 3 versions.
New release 1.4.0 so the latest 3 versions are different.
N/A
1.4.0 release currently ongoing, tag may not exist yet.
**Checklist:**
=> chore: update regression versions for workflow

gdk/build_system/Zip.py, integration_tests/gdk/components/test_integ_BuildCommand.py
https://github.com/aws-greengrass/aws-greengrass-gdk-cli/issues/143
Only exclude excluded files from the zip build, if they are in the root directory of the build.
See issue for correspondence. Certain projects may need to include files in sub-directories that were incorrectly being excluded.
Manually tested using a sample project that had test* prefixed files in both root directory and sub-directories. Change correctly packages it such that the excluded files in root are removed but the ones not in root were kept.
Updated integration test for build command to verify that test* prefixed file in src subfolder is kept, but test* prefixed file in root folder is excluded …
=> fix: only exclude files from root dir when building zip

gdk/build_system/Zip.py, integration_tests/gdk/components/test_integ_BuildCommand.py, tests/gdk/build_system/test_Zip.py
Change the default behavior for zip build to exclude test from all subdirectories, consistent with past GDK versions (1.4.0 and before).
Changing default behavior to be in line with past behavior.
I changed the tests that had to do with default behavior. Also verified that the change worked as expected manually.
**Checklist:**
=> feat: exclude test from all subdirectories by default

gdk/build_system/Zip.py, integration_tests/gdk/components/test_integ_BuildCommand.py, integration_tests/test_data/config/config_new_excludes.json, integration_tests/test_data/config/config_old_excludes.json
Adds a smart warning during component build that notifies user of the glob behavior change during zip exclusions if their provided excludes config uses exclusively the patterns that do not match to directories (old format). The warning also informs the user of how to achieve the old behavior by updating their config and specifies the exact change that needs to be made for this to happen.
The warning can be ignored by setting the GDK_EXCLUDES_WARN_IGNORE environment variable to true.
Example output (given ["node_modules"] as the excludes config):
`[2023-10-24 15:47:07] WARNING - Build option 'excludes' found in config and none of the provided patterns include directory matching. In GDK version 1.5.0, patterns for exclusions in zip …
=> feat: add smart warning if old excludes config is provided

.github/workflows/Regression.yaml
Bumping the versions that the regression workflow tests against due to newest release of 1.5.0. 
Allow future development to test against latest 3 versions (including existing)
N/A
**Checklist:**
=> chore: update regression versions to test latest 1.5.0

gdk/commands/component/transformer/BuildRecipeTransformer.py, gdk/commands/component/transformer/PublishRecipeTransformer.py, gdk/common/RecipeValidator.py, gdk/common/consts.py, gdk/common/exceptions/error_messages.py, gdk/static/recipe_schema.json, integration_tests/gdk/common/test_integ_recipe_schema.py, integration_tests/gdk/components/test_integ_BuildCommand.py, integration_tests/gdk/components/test_integ_PublishCommand.py, integration_tests/test_data/recipes/build_recipe_invalid.yaml, integration_tests/test_data/recipes/hello_world_recipe_invalid.yaml, tests/gdk/common/test_RecipeValidator.py
Adds the Greengrass recipe schema to GDK. This is temporary until a more permanent solution to pull the schema down from a cloud source is added.
Add recipe schema validation to the component build and component publish commands. These will compare the project recipe file against the included Greengrass recipe schema and stop the command and produce a ValidationError if the recipe does not validate against the schema.
Validating component recipes against the schema is a planned feature and allows users of GDK to identify issues with their recipes earlier in the development process.
Manually tested. Added unit/integration tests for the additions.
**Any additional …
=> feat: add recipe validation to build and publish commands

gdk/static/recipe_schema.json
Global flags must be in front of the regex expression in python 3.11+. This PR moves them there for regex instances that have them in the schema.
Maintain compatibility with later versions of python.
Using python 3.12, with these changes I no longer get warnings/errors about the regex.
**Checklist:**
=> fix: fix regex format for python 3.11+

gdk/commands/component/transformer/PublishRecipeTransformer.py, gdk/common/exceptions/error_messages.py
Followup from discussion here: https://github.com/aws-greengrass/aws-greengrass-gdk-cli/pull/262#discussion_r1393370377
Have both build and publish commands use the same invalid recipe error.
Keeps the code simple and cleaner with less items to update when we wish to change the error message.
Unit/Integration tests pass, manually tested
**Checklist:**
=> refactor: consolidate similar error messages about invalid recipes

gdk/common/GithubUtils.py, gdk/common/config/TestConfiguration.py, gdk/common/consts.py, integration_tests/gdk/common/config/test_GDKProject.py, integration_tests/gdk/test/test_integ_uat_InitCommand.py, tests/gdk/commands/test/config/test_InitConfiguration.py, tests/gdk/common/test_GithubUtils.py
Get the latest GTF release name from Github API and use it as the default value. If this API request fails (typically due to exceeding rate limits), fall bad on old behavior and use a hard-coded release value.
Getting the release dynamically should allow customers to benefit from GTF releases as soon as they are available, and lessen the need for us to release new GDK versions to followup GTF releases. The hard coded value will still need to be updated once in a while though.
Modified unit and integration tests that use the config value. Added new unit test for the new utils function. Manually tested as well.
**Any additional information or context required to review …
=> feat: get latest GTF release name from Github API

gdk/common/config/TestConfiguration.py
Changes some debug logs for grabbing the latest GTF release from info level logging to debug. These statements will appear on any command as they are run when setting up the tool configuration and we shouldn't show them by default.
Keep the cli tool output clean. We don't want to always display this information and especially not when a command unrelated to e2e testing is run.
Manually tested and the logs show with the debug flag and not otherwise. No unit/integration testing required.
**Checklist:**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
=> chore: update logging level for latest gtf release logs

setup.py
Setuptools build includes only gdk package. Test-related packages are excluded.
Build package currently contains `tests` and `integration_tests`. These are common in many projects which lead to name collisions. In my case, I spotted the issue when Pycharm tried to search for project tests in the gdk installed tests package.
`python setup.py build`, results verified visually.
**Checklist:**
=> fix(setuptools): exclude test related packages from build

setup.py
Include packages from subdirectories when building. This should fix failing workflows on commit https://github.com/aws-greengrass/aws-greengrass-gdk-cli/commit/3545476003eb5b9a2907e05794352db4b908f94e
python3 setup.py build no longer warns about missing gdk.common from the build.
**Checklist:**
=> fix: include packages from subdirectories of gdk

.github/workflows/CI.yml
During our CI steps add installation of the CLI/its dependencies. We do this in our regression steps but doing this here will help us spot issues sooner.
Help spot issues sooner.
Workflow on this PR. At the time of writing, the workflows are failing as https://github.com/aws-greengrass/aws-greengrass-gdk-cli/pull/279 fix is still waiting to be merged.
**Checklist:**
=> chore: add cli and dependencies installation to CI steps
