aws-greengrass/aws-greengrass-gdk-cli

.github/workflows/CI.yml
Checks if the commit message follows convention.
**Checklist:**
=> chore(workflow): add check for commit message

uat/test_uat_CLIParser.py
Add tests for build command with HelloWorld python template. 
Basic UAT for template build using cli on multiple platforms.
Tested UATs with reverted fix - https://github.com/aws-greengrass/aws-greengrass-gdk-cli/runs/4512816920?check_suite_focus=true#step:8:304. Fails as expected. 
**Checklist:**
=> test(uat): add uat cli build command

gdk/static/cli_model_schema.json, integration_tests/gdk/common/test_integ_model_actions.py
Add json schema validation for cli model. Validate the cli model with its schema in integration test.
Helps other developers understand the cli model better as the schema contains description of the model. 
**Checklist:**
=> refactor(cli-model): add schema validation for cli model

gdk/commands/component/publish.py, tests/gdk/commands/component/test_publish.py
If the component artifacts are not build, publish command exits displaying a log. With this change, component builds before publishing if it is not already build. Otherwise, the command directly publishes the component. 
Customers can now create component versions in one command instead of 2 if the component is not build already. 
Updated old tests and added new ones.
**Checklist:**
=> refactor(publish): build before publish

.github/workflows/CI.yml
Upload coverage report with codecov github action in the workflow. 
**Checklist:**
=> chore(workflow): upload coverage with codecov action

uat/test_uat_CLIParser.py
=> test(uat): build with no artifacts + use fixture 

gdk/commands/component/build.py, tests/gdk/commands/component/test_build.py
- Fix bug in reading response. 
- Add docstrings
- Rename `copy_artifacts_and_update_uris` to `find_artifacts_and_update_uri`
Properly read the status from response object. 
**Checklist:**
=> fix(s3-artifacts): get status from response metadata + docstrings

gdk/commands/component/list.py, gdk/common/configuration.py, integration_tests/gdk/common/test_integ_configuration.py, integration_tests/gdk/common/test_integ_model_actions.py, integration_tests/gdk/common/test_integ_parse_args_actions.py, integration_tests/gdk/components/test_integ_list.py, integration_tests/gdk/components/test_integ_project_utils.py, tests/gdk/commands/component/test_project_utils.py, tests/gdk/common/test_configuration.py, tests/gdk/common/test_model_actions.py, tests/gdk/common/test_parse_args_actions.py
Add integration tests for list, config, model actions, parse args & project utils
**Checklist:**
=> test: add integration tests for list, config, model actions, parse args & project utils

gdk/commands/component/PublishCommand.py, gdk/commands/component/component.py, integration_tests/gdk/components/test_integ_InitCommand.py, uat/t_utils.py, uat/test_uat_build.py, uat/test_uat_init.py, uat/test_uat_list.py, uat/test_uat_publish.py
- Add uats and improve the coverage to 81%. 
- Fix typos
Clean up. 
**Checklist:**
=> refactor: fix typos + add uats to improve coverage

.github/dependabot.yml, .github/workflows/CI.yml, .github/workflows/auto-approve.yml
Add dependabot config to create pull-requests based on dependency updates. Also add auto-approve workflow to merge pull-requests with `auto-approve` labels.
To keep dependencies up-to date.
**Checklist:**
=> chore: add dependabot config & auto-approve workflow

.github/workflows/CI.yml, integration_tests/gdk/components/test_integ_BuildCommand.py, uat/conftest.py, uat/t_setup.py, uat/t_utils.py, uat/test_uat_publish.py
Add multiple python versions to verify regression between python versions.
With workflows runs as part of this pull request.
**Checklist:**
=> chore: add python versions for regression test

tests/gdk/commands/component/test_PublishCommand.py, tests/gdk/commands/test_Command.py, uat/test_uat_build.py, uat/test_uat_publish.py
- Update GitHub secrets to pick new test account role. 
- Update test bucket names to reflect changes.
- Do minor cleanup.
Use new test account. 
**Checklist:**
=> test: update test account + cleanup

.github/workflows/CI.yml, README.md
Update docs changes from https://github.com/aws-greengrass/aws-greengrass-gdk-cli/pull/102
**Checklist:**
=> docs: update readme with gdk-config.json config step

.gitignore, gdk/build_system/BuildSystem.py, gdk/build_system/Zip.py, gdk/build_system/__init__.py, gdk/commands/Command.py, gdk/commands/component/BuildCommand.py, tests/gdk/build_system/test_BuildSystem.py, tests/gdk/commands/component/test_BuildCommand.py
Currently everything is under a single class and expanding functionality will just keep tangling this up. This changes will allow us to start extracting the build logic into its own classes to we can expand them separately
Extract zip logic to a class and delegate.
UATs are passing locally with the creds
=> refactor: zip build

tests/gdk/build_system/test_zip_build_configuration.py
Remove an old test. This is covered on the test_Zip.py file
=> fix: remove old test

gdk/commands/component/PublishCommand.py, tests/gdk/commands/component/test_PublishCommand.py
- This change first verifies if the component is built.
- Then updates the project configuration values such as account number, bucket, version in order based on the publish configuration. 
**Checklist:**
=> refactor: clean up PublishCommand class

uat/component_list.feature
Fix UAT that's failing in regressions due to incorrect version. 
**Checklist:**
=> tets: fix uat list templates

README.md
Update the instructions in the README to install v1.2.0 of GDK.
**Checklist:**
=> chore: update readme with instructions to install v1.2.0

.github/dependabot.yml, .github/workflows/CI.yml, .github/workflows/Regression.yaml, .github/workflows/auto-approve.yml
#130 , #129 , #128 , #127 , #126 
**Checklist:**
=> chore: update github actions deps

README.md
Update README file for v1.2.2 release. 
**Checklist:**
=> chore: update readme for v1.2.2

gdk/telemetry/emit.py, gdk/telemetry/telemetry_config.py, integration_tests/gdk/telemetry/telemetry_base.py, integration_tests/gdk/telemetry/test_emit_telemetry.py, tests/gdk/telemetry/test_emit.py, tests/gdk/telemetry/test_telemetry_config.py, tests/test_runtime_config.py
Displays a telemetry metric prompt the first time the CLI is installed. Additionally refactored some names to better reflect what they are storing
Notify the user that we are collecting telemetry data
Unit tests and integ
=> telemetry prompt

gdk/telemetry/emit.py, tests/gdk/telemetry/test_emit.py
Build is failing on the development branch `ModuleNotFoundError: No module named 'click'` not sure why the builds passed before we merged it and now they are failing on development. 
Pass build
Tests passing
=> Fix prompt output

gdk/common/URLDownloader.py, integration_tests/gdk/common/test_integ_URLDownloader.py, tests/gdk/common/test_URLDownloader.py
Add a utility method to download a file from URL to the specified location. 
- Existing code does the same will be refactored to use this in the later PRs. 
**Checklist:**
=> feat: add URLDownloader utility method

gdk/commands/test/RunCommand.py, tests/gdk/commands/test/test_uat_RunCommand.py
This change helps gdk identify testing jar from the build output. The testing module build process may generate multiple jar files based on the customer's configuration. When customer runs `gdk test run` command, gdk should identify the testing jar and run it for the customers with the provided options. 
gdk first checks for `uat-features-1.0.0.jar ` in the build folder as that's the default output if the module is built from the sample template. 
If the default jar is not present, then all the `.jar` files in the build folders are run with `--help` command and their output is tested.If the output contains `gg-test`, then it is identified as a testing jar and the tests are run with it. 
**How was this …
=> feat: identify testing jar from the build folder

gdk/commands/test/BuildCommand.py, tests/gdk/commands/test/test_uat_BuildCommand.py
If `NEXT_PATCH` is specified in gdk_config.json file, build recipe is created with  component version as`NEXT_PATCH`. Since test recipe is created from build recipe, this version must be updated to a valid semver as the testing framework cannot create a  component if `NEXT_PATCH` version.
**Checklist:**
=> fix: replace NEXT_PATCH with 1.0.0 for component version in test recipe

gdk/aws_clients/Greengrassv2Client.py, gdk/aws_clients/S3Client.py, gdk/commands/component/PublishCommand.py, tests/gdk/aws_clients/test_Greengrassv2Client.py, tests/gdk/aws_clients/test_S3Client.py, tests/gdk/commands/component/test_PublishCommand.py
- Refactor AWS client methods in such a way that they don't depend on project configuration. 
- Update tests for the same. 
**Checklist:**
=> refactor: refactor client methods

THIRD-PARTY-LICENSES
=> chore: update licenses

README.md
=> chore: update readme for gdk 1.3.0 release

gdk/wizard/ConfigEnum.py, gdk/wizard/WizardData.py, test-requirements.txt, tests/gdk/wizard/test_WizardData.py
Wizard Data used for getting and setting config key values 
tested through unit testing of all getter and setter methods 
**Checklist:**
=> Wizard data

gdk/wizard/WizardChecker.py, tests/gdk/wizard/test_WizardChecker.py
wizard input validator and test cases 
In order to valid the input responses of the customers to the prompt questions about field key values 
unit testing 
Todo: Next PR will include validators along with test cases for build options, the publish configuration, and gdk version
**Checklist:**
=> feat: wizard input validator and test cases 

gdk/wizard/WizardChecker.py, tests/gdk/wizard/test_WizardChecker.py
wizard input checker for build option, publish configs, and gdk_version
Tested through unit testing 
**Checklist:**
=> feat: validation and test for rest of fields

gdk/wizard/Prompter.py, gdk/wizard/WizardChecker.py, gdk/wizard/WizardConfigUtils.py, gdk/wizard/WizardData.py, tests/gdk/wizard/test_WizardChecker.py, tests/gdk/wizard/test_WizardData.py
Wizard prompter
prompters users to populate config key values 
This change has not yet been tested
**Checklist:**
=> feat: Wizard prompter 

gdk/commands/component/WizardCommand.py, gdk/commands/component/component.py, gdk/commands/methods.py, gdk/static/cli_model.json
Wizard integration into existing CLI
Will be tested using integration testing
**Checklist:**
=> feat: Wizard command Integration

gdk/commands/component/transformer/BuildRecipeTransformer.py, gdk/common/RecipeValidator.py, gdk/common/consts.py, gdk/common/exceptions/error_messages.py, gdk/common/exceptions/syntax_error_message.py, gdk/common/utils.py, tests/gdk/commands/component/transformer/test_BuildRecipeTransformer.py, tests/gdk/common/test_RecipeValidator.py, tests/gdk/common/test_utils.py
Implemented semantic validation for recipe files and included corresponding unit tests. Introduced the capability to parse validation errors if any issues arise in the recipe's structure or input options. Additionally, the validation flow has been integrated into the build stage, ensuring that user input recipes are thoroughly validated before proceeding with the transformation into the build directory.
This enhancement is crucial to guarantee the integrity of recipe data and to prevent downstream issues during processing and deployment.
Added unit tests to validate the functionality, and all unit tests (including the new ones) and integration tests passed successfully. …
=> feat: add recipe semantic validation

gdk/common/RecipeValidator.py, gdk/common/consts.py, gdk/common/utils.py, gdk/static/user_input_recipe_schema.json, tests/gdk/commands/component/transformer/test_BuildRecipeTransformer.py, tests/gdk/common/test_RecipeValidator.py, tests/gdk/common/test_utils.py
Updated the recipe schema to CamelCase as documented in the [AWS IoT Greengrass component recipe reference](https://docs.aws.amazon.com/greengrass/v2/developerguide/component-recipe-reference.html) and changed the corresponding validation to align with the recipe schema.
This change is necessary to improve the error logging message and make it more informative, in line with user input expectations.
New unit tests were added, and all tests passed successfully. Additionally, the manual testing was conducted to ensure it functions as expected.
**Checklist:**
By submitting this pull request, I confirm …
=> feat: update recipe schema to recommended CamelCase

codecov.yml, gdk/commands/component/WizardCommand.py, gdk/commands/component/component.py, gdk/commands/methods.py, gdk/static/cli_model.json, gdk/wizard/ConfigEnum.py, gdk/wizard/Prompter.py, gdk/wizard/WizardChecker.py, gdk/wizard/WizardConfigUtils.py, gdk/wizard/WizardData.py, requirements.txt, test-requirements.txt, tests/gdk/wizard/test_WizardChecker.py, tests/gdk/wizard/test_WizardData.py
Add "wizard" feature (gdk component wizard command). This command creates an interactive shell experience to modify the gdk-config.json file. Changes are already reviewed in separate PRs into this branch.
New feature to be included.
Unit tests are added for the feature. 
Additional work on this feature (including renaming the command) will be done later. This PR is just merging in the existing work from this branch.
**Checklist:**
=> Initial implementation of config component command
